# Must set the following environment variables in the pipeline:
#
# - GIT_PRIVATE_KEY_BASE64 (encrypted)
#
version: "1.0"
stages:
- build
- test
- release
steps:
  CheckVersions:
    image: alpine/git:1.0.4
    commands:
    - export CHART_VERSION=$(cat helm-charts/rainbow-kitten-surprise/Chart.yaml | grep -m 1 ^version:| awk '{print $2}')
    - export DOCKER_VERSION=$(cat services/cat-service/VERSION)
    - export PUSH_DOCKER=$(if [[ "$(git log --format='%H' -n 1 -- services/cat-service/VERSION)" == "${{CF_REVISION}}" ]]; then echo "true"; else echo "false"; fi)
    - cf_export CHART_VERSION=$CHART_VERSION DOCKER_VERSION=$DOCKER_VERSION PUSH_DOCKER=$PUSH_DOCKER
  BuildDocker:
    stage: build
    type: build
    working_directory: services/cat-service/
    image_name: azure-helm-webinar/cat-service
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
  TestDocker:
    stage: test
    image: alpine/git:1.0.4
    commands:
    - echo "tests pass"
  PushDocker:
    stage: release
    type: push
    candidate: '${{BuildDocker}}'
    tag: '${{DOCKER_VERSION}}'
    registry: acr
    when:
      condition:
        all:
          VersionChanged: '"${{PUSH_DOCKER}}" == "true"'
  BumpChartVersion:
    stage: release
    image: andthensome/alpine-hugo-git-bash:latest
    commands:
    - export NEW_CHART_VERSION=$(bash -c 'A=( ${CHART_VERSION//./ } ); ((A[1]++)); echo ${A[0]}.${A[1]}.${A[2]}')
    - echo "old chart version - $CHART_VERSION"
    - echo "new chart version - $NEW_CHART_VERSION"
    - sed -i "s/$CHART_VERSION/$NEW_CHART_VERSION/g" helm-charts/rainbow-kitten-surprise/Chart.yaml
    - 'sed -i "s/catImageTag: \".*\"/catImageTag: \"$DOCKER_VERSION\"/g" helm-charts/rainbow-kitten-surprise/values.yaml'
    - git config --global user.email robot@codefresh.io
    - git config --global user.name robot
    - git commit -am "Automated - new version $NEW_CHART_VERSION"
    - apk update && apk add openssh
    - mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
    - echo $GIT_PRIVATE_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa'
    - git push git@github.com:codefresh-io/azure-helm-webinar.git HEAD:master
    when:
      condition:
        all:
          VersionChanged: '"${{PUSH_DOCKER}}" == "true"'
