# obtain this from Azure portal and install this chart with --set clusterDnsZone=<zone>
# clusterDnsZone: "52fc7454c071a75fc1d3.eastus.aksapp.io"

catImageName: "joshtest.azurecr.io/azure-helm-webinar/cat-service"
catImageTag: "0.6.1"

colorImageName: "joshtest.azurecr.io/azure-helm-webinar/color-service"
colorImageTag: "0.6.2"
